pkgname=omen-fan-git
pkgver=r30.dc2aa13
pkgrel=1
pkgdesc="Utility and daemon to control fans in HP Omen laptops"
arch=('any')
url="https://github.com/alou-S/omen-fan"
license=('GPL3')
depends=('python' 'python-click' 'python-tomlkit' 'python-click-aliases')
makedepends=('git')
backup=('etc/omen-fan/config.toml')
source=("git+https://github.com/alou-S/omen-fan.git")
md5sums=('SKIP')

pkgver() {
  cd omen-fan
  printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"
}

package() {
  cd omen-fan

  # Install binaries without .py extension
  install -Dm755 omen-fan.py "$pkgdir/usr/bin/omen-fan"
  install -Dm755 omen-fand.py "$pkgdir/usr/bin/omen-fand"

  # Install documentation
  install -Dm644 README.md "$pkgdir/usr/share/doc/$pkgname/README.md"

  # Generate and install default config.toml
  install -d "$pkgdir/etc/omen-fan"
  cat <<EOF > "$pkgdir/etc/omen-fan/config.toml"
# Generated by omen-fan-git PKGBUILD

[service]
TEMP_CURVE = [45, 55, 65, 75, 80, 85]
SPEED_CURVE = [30, 45, 65, 85, 95, 100]
IDLE_SPEED = 25
POLL_INTERVAL = 1.0

[script]
BYPASS_DEVICE_CHECK = 1
EOF
  chmod 644 "$pkgdir/etc/omen-fan/config.toml"

  # Generate and install systemd service
  install -d "$pkgdir/usr/lib/systemd/system"
  cat <<EOF > "$pkgdir/usr/lib/systemd/system/omen-fan.service"
[Unit]
Description=HP Omen Fan Control Daemon
After=multi-user.target

[Service]
Type=simple
ExecStart=/usr/bin/omen-fand
Restart=on-failure

[Install]
WantedBy=multi-user.target
EOF
  chmod 644 "$pkgdir/usr/lib/systemd/system/omen-fan.service"
}
